name: NGS
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - bcrypt=5.0.0=py310hd8f68c5_1
  - boto3=1.42.28=pyhd8ed1ab_0
  - botocore=1.42.28=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - coin-or-cbc=2.10.12=h4d16d09_5
  - coin-or-cgl=0.60.9=hc46dffc_7
  - coin-or-clp=1.17.10=hc03379b_4
  - coin-or-osi=0.108.11=hf4fecb4_8
  - coin-or-utils=2.11.12=hc93afbd_7
  - coincbc=2.10.12=5_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.2=py310h3788b33_0
  - cryptography=46.0.3=py310hb288b08_1
  - cutadapt=5.2=py310h1fe012e_0
  - cycler=0.12.1=pyhcf101f3_2
  - datrie=0.8.3=py310h7c4b9e2_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dnaio=1.2.2=py310h7c593f9_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_1
  - dropbox=12.0.2=pyhd8ed1ab_1
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastqc=0.12.1=hdfd78af_0
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py310h9548a50_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - google-api-core=2.29.0=pyhd8ed1ab_0
  - google-api-python-client=2.188.0=pyh332efcf_0
  - google-auth=2.47.0=pyhcf101f3_0
  - google-auth-httplib2=0.3.0=pyhd8ed1ab_0
  - google-cloud-core=2.5.0=py310h06a4308_0
  - google-cloud-storage=3.8.0=pyhcf101f3_0
  - google-crc32c=1.8.0=py310hf432777_0
  - google-resumable-media=2.8.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h6083320_0
  - hisat2=2.2.1=h503566f_8
  - hpack=4.1.0=pyhd8ed1ab_0
  - htseq=2.0.9=py310ha1cbcee_0
  - htslib=1.22.1=h566b1c6_0
  - httplib2=0.31.1=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - immutables=0.21=py310h7c4b9e2_2
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - invoke=2.2.1=pyhd8ed1ab_0
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - legacy-cgi=2.6.4=pyhcf101f3_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250814.1=cxx17_hee66210_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multidict=6.7.0=py310h3406613_0
  - munkres=1.0.7=py_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=1.26.4=py310hb13e2d6_0
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_2
  - paramiko=4.0.0=pyhd8ed1ab_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.47=haa7fec5_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.8=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.8=h421ea60_2
  - pillow=12.1.0=py310h5a73078_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - propcache=0.3.1=py310h89163eb_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - protobuf=6.32.1=py310h406790d_2
  - psutil=7.2.1=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.7.0=py310hff52083_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.2=py310h7c4b9e2_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysam=0.23.3=py310h64e62c9_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-irodsclient=3.1.1=pyhff2d567_1
  - python-isal=1.8.0=py310h7c4b9e2_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-zlib-ng=1.0.0=py310ha25ff1b_1
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.30.0=py310hd8f68c5_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - samtools=1.22.1=h96c455f_0
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.9.0=pyhff2d567_0
  - setuptools-scm=9.2.2=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - slack-sdk=3.39.0=pyhd8ed1ab_0
  - slack_sdk=3.39.0=hd8ed1ab_0
  - slacker=0.14.0=pyhd8ed1ab_1
  - smart_open=7.5.0=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-interface-common=1.22.0=pyhd4c3c12_0
  - snakemake-interface-executor-plugins=8.1.1=pyhdfd78af_0
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - star=2.7.11b=h5ca1c30_8
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - subread=2.1.1=h577a1d6_0
  - tabulate=0.9.0=pyhcf101f3_3
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.4.0=pyhcf101f3_0
  - toposort=1.10=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trim-galore=0.6.10=hdfd78af_2
  - trimmomatic=0.40=hdfd78af_0
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.1=py310h7c4b9e2_1
  - xopen=2.0.2=pyh707e725_2
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - yte=1.9.4=pyhd8ed1ab_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - path==17.1.1
